OA.Web/Controllers/MeetingRoomController.cs
using OA.Common;
using OA.Model;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace OA.Web.Controllers
{
    public class MeetingRoomController : CommonController
    {
        MeetingRoomData db = new MeetingRoomData();
        /// <summary>
        /// 返回视图
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            return View();
        }
        /// <summary>
        /// 分页查询
        /// </summary>
        /// <param name="id">当前页</param>
        /// <param name="page">当前页</param>
        /// <param name="searchMsg">会议室名称</param>
        /// <param name="IsValid">是否可用</param>
        /// <returns></returns>
        public ActionResult List_Json(int? id,int? page, string searchMsg, bool IsValid)
        {
            int pageIndex = page ?? 1;
            const int pageSize = 10;
            IEnumerable<MeetRoom> list = db.GetListByMe(pageIndex, pageSize, searchMsg, IsValid);
            int rowCount = db.GetListAll(searchMsg, IsValid).Count();
            var pageCount = 0;
            if (rowCount % pageSize != 0)
            {
                if (rowCount - pageSize < 0)
                {
                    pageCount = 1;
                }
                else
                {
                    pageCount = rowCount / pageSize + 1;
                }
            }
            else
            {
                pageCount = rowCount / pageSize;
            }
            var strResult = "{\"pageCount\":" + pageCount + ",\"CurrentPage\":" + pageIndex + ",\"list\":" + list.ToJsonString() + "}";
            return Json(strResult, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 创建及修改获取会议室
        /// </summary>
        /// <param name="id">会议室ID</param>
        /// <returns></returns>
        public ActionResult CreateAndEditer(int? id)
        {
            MeetRoom emp = null;
            if (id != null)
            {
                emp = db.GetModel(id.Value);
            }
            if (emp == null)
                emp = new MeetRoom();
            return View(emp);
        }

        /// <summary>
        /// 保存会议室信息
        /// </summary>
        /// <param name="id">会议室ID</param>
        /// <param name="remark">备注</param>
        /// <param name="person">容纳人数</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateAndEditer(int? id,string name,string remark,int person)
        {
            MeetRoom currentRoom;
            if (id == 0||id==null)  { currentRoom = new MeetRoom(); }
            else { currentRoom = db.GetModel(int.Parse(id.ToString())); }
            currentRoom.RoomName = name;
            currentRoom.Person =person;
            currentRoom.Remark  =remark;
            currentRoom.IsValid = true;
            db.Save(currentRoom);
            return Json("OK");
        }

        /// <summary>
        /// 删除会议室
        /// </summary>
        /// <param name="Id">会议室Id</param>
        public JsonResult Delete(int Id)
        {
            db.Detail(Id);
            return Json("yes");
        }
        /// <summary>
        /// 设置为不可用
        /// </summary>
        /// <param name="id">会议室Id</param>
        /// <returns></returns>
        public ActionResult ValidChangeNo(int id)
        {
            db.ValidChangeNo(id);
            return View("List");
        }

        /// <summary>
        /// 设置为可用
        /// </summary>
        /// <param name="id">会议室Id</param>
        /// <returns></returns>
        public ActionResult ValidChangeYes(int id)
        {
            db.ValidChangeYes(id);
            return View("List");
        }
    }
}

OA.Web/Views/MeetingRoom/CreateAndEditer.cshtml
@model OA.Model.MeetRoom

@{
    ViewBag.Title = "CreateAndEditer";
    Layout = "~/Views/Shared/_JsCss.cshtml";
}
<script type="text/javascript">
    $(function () {
        //提交事件
        $(".btn").on("click", function (event) {
            event.preventDefault()
            if ($("#RoomName").val() == null || $("#RoomName").val() == "") {
                alert("会议室名不能为空！")
                return null;
            }
            if ($("#Person").val() == null || $("#RoomName").val() == "") {
                alert("容纳人数不能为空！")
                return null;
            }
            $.ajax({
                url: "CreateAndEditer",
                type: "post",
                data: {
                    name: $("#RoomName").val(),
                    id: $("#RoomId").val(),
                    remark: $("#Remark").val(),
                    person: $("#Person").val()
                },
                success: function (result) {
                    if (result !== null) {
                        alert("保存成功！");
                    }
                }
            });
            return false;
        });
    })
</script>

<h2>会议室信息</h2>
@using (Html.BeginForm("CreateAndEditer", "MeetingRoom", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <fieldset>
        <legend>@Html.ActionLink("返回", "List")</legend>
        <div class="form-group">
            <input type="hidden" id="EmpId" />
            @Html.HiddenFor(model => model.RoomId)
            <label class="col-sm-4 control-label" for="RoomName">会议室名</label>
            <div class="col-sm-5">
                @Html.EditorFor(model => model.RoomName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.RoomName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label" for="Person">可容纳人数</label>
            <div class="col-sm-5">
                @Html.EditorFor(model => model.Person, new { htmlAttributes = new { @class = "form-control", required = "required", type = "number" } })
                @Html.ValidationMessageFor(model => model.Person, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label" for="Remark">备注</label>
            <div class="col-sm-5">
                @Html.TextAreaFor(model => model.Remark, 4, 60, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-6"></div>
            <div class="col-sm-5">
                <input type="button" value="提交" class="btn btn-default" />
            </div>
        </div>
    </fieldset>
}

OA.Web/Views/MeetingRoom/List.cshtml
@model IEnumerable<OA.Model.MeetRoom>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_JsCss.cshtml";
}
<script src="~/Scripts/bootstrap-paginator.js"></script>
<script type="text/javascript">
    $(function () {
        loadPage();
        function loadPage() {
            $.ajax({
                url: "List_Json",
                type: "post",
                data: { searchMsg: $("#serachText").val(), IsValid: $("#IsValid").val() },
                success: function (data) {
                    if (data != null) {
                        addToList(data);
                        var pageCount = eval("(" + data + ")").pageCount; //取到pageCount的值(把返回数据转成object类型)
                        var currentPage = eval("(" + data + ")").CurrentPage; //得到CurrentPage
                        var options = {
                            bootstrapMajorVersion: 2, //版本
                            currentPage: currentPage, //当前页数
                            totalPages: pageCount, //总页数
                            itemTexts: function (type, page, current) {
                                switch (type) {
                                    case "first":
                                        return "首页";
                                    case "prev":
                                        return "上一页";
                                    case "next":
                                        return "下一页";
                                    case "last":
                                        return "末页";
                                    case "page":
                                        return page;
                                }
                            },//点击事件，用于通过Ajax来刷新整个list列表
                            onPageClicked: function (event, originalEvent, type, page) {
                                $("#List").empty();
                                $("#pager").hide();
                                $.ajax({
                                    url: "List_Json" + "?id=" + page,
                                    type: "Post",
                                    data: { page: page, searchMsg: $("#serachText").val(), IsValid: $("#IsValid").val() },
                                    success: function (data1) {
                                        if (data1 != null) {
                                            addToList(data1);
                                        }
                                        $("#pager").show();
                                    }
                                });
                            }
                        };
                        $("#pager").bootstrapPaginator(options);
                    }
                }
            })
        }

            $("#serachBtn").click(function () {
                $("#List").empty();
                $("#pager").hide();
                loadPage();
                $("#pager").show();
            })
    })
        function addToList(data) {
            $("#List").append('<table id="data_table" class="table table-striped"> <thead><tr><th>会议室名</th><th>可容纳人数</th><th>备注</th><th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;操  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;作</th></tr><tbody></tbody></table>');
            $.each(eval("(" + data + ")").list, function (index, item) { //遍历返回的json
                str = item.IsValid == true ? '<a class="valid" id=' + item.RoomId + '  href="ValidChangeNo?id=' + item.RoomId + '">设为不可用&nbsp;</a>' : '<a class="valid" id='
                    + item.RoomId + '  href="ValidChangeYes?id=' + item.RoomId + '">设为可用&nbsp;</a>'
                $("#data_table tbody").append('<tr><td>' + item.RoomName + '</td><td>' + item.Person + '</td><td>'
                    + item.Remark + '</td><td>' + str + '<a class="edit" id=' + item.RoomId + '  href="CreateAndEditer?id=' +
                    item.RoomId + '">修改</a> <a class="confirm-link" id="delete" href="#" onclick="deleteFunc(' + item.RoomId + ')">删除</a></td></tr>');
            });
        }
        function deleteFunc(roomId) {
            var r = confirm("确认删除这条数据");
            if (r == true) {
                $.ajax({
                    url: "delete?id=" + roomId,
                    datatype: "json",
                    type: "Post",
                    success: function (data) {
                        if (data == "yes") {
                            $("#List").empty();
                            $("#pager").empty();
                            $.ajax({
                                url: "List_Json",
                                datatype: "json",
                                type: "Post",
                                data: { searchMsg: $("#serachText").val(), IsValid: $("#IsValid").val() },
                                success: function (data) {
                                    if (data != null) {
                                        addToList(data);
                                        var pageCount = eval("(" + data + ")").pageCount; //取到pageCount的值(把返回数据转成object类型)
                                        var currentPage = eval("(" + data + ")").CurrentPage; //得到CurrentPage
                                        var options = {
                                            bootstrapMajorVersion: 2, //版本
                                            currentPage: currentPage, //当前页数
                                            totalPages: pageCount, //总页数
                                            itemTexts: function (type, page, current) {
                                                switch (type) {
                                                    case "first":
                                                        return "首页";
                                                    case "prev":
                                                        return "上一页";
                                                    case "next":
                                                        return "下一页";
                                                    case "last":
                                                        return "末页";
                                                    case "page":
                                                        return page;
                                                }
                                            },//点击事件，用于通过Ajax来刷新整个list列表
                                            onPageClicked: function (event, originalEvent, type, page) {
                                                $("#List").empty();
                                                $("#pager").hide();
                                                $.ajax({
                                                    url: "List_Json",
                                                    type: "Post",
                                                    data: { page: page, searchMsg: $("#serachText").val(), IsValid: $("#IsValid").val() },
                                                    success: function (data1) {
                                                        if (data1 != null) {
                                                            addToList(data1);
                                                        }
                                                        $("#pager").show();
                                                    }
                                                });
                                            }
                                        };
                                        $("#pager").bootstrapPaginator(options);
                                    }
                                    alert("删除成功");
                                }
                            });
                        }
                        else {
                            alert("删除失败");
                        }
                    }
                })
            }
        }
</script>
@*<style type="text/css">
    button a {
        color: white;
        text-decoration-line: none;
    }

        button a:hover {
            color: white;
            text-decoration-line: none;
        }
</style>*@



<body style="width:100%;padding-top:10px;">
    <div class="input-group col-sm-2" style="margin-bottom:5px;position:relative">
        @Html.DropDownList("IsValid", new List<SelectListItem>
        {
            ( new SelectListItem() { Text="可用",Value="true",Selected=true}),
            (new SelectListItem() { Text="不可用",Value="false",Selected=false})
        }, new { @class = "form-control" })
    </div>
    <div class="input-group col-sm-3" style="margin-bottom:5px;position:relative">
        <input type="text" class="form-control" id="serachText" placeholder="请输入会议室姓名" style="width:150px;">
        <span class="input-group-btn">
            <button class="btn btn-info bt-search" id="serachBtn">查找</button>
            <button class="btn btn-info bt-search" style="margin-left:3px;color:white;">@Html.ActionLink("新增会议室", "CreateAndEditer")</button>
        </span>
    </div>
    <div id="List"></div>
    <div id="pager"></div>
</body>