OA.Web/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OA.Model;
using OA.Common;

namespace OA.Web.Controllers
{
    public class ClientController : Controller
    {
        ClientData db = new ClientData();
        #region 客户
        /// <summary>
        /// 返回页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 分页查询
        /// </summary>
        /// <param name="page">当前页</param>
        /// <param name="searchMsg">客户姓名</param>
        /// <param name="CType">客户类型</param>
        /// <param name="Status">有效性</param>
        /// <returns></returns>
        public JsonResult List_Json(int? page,string searchMsg,int CType,bool Status)
        {
            int pageIndex=page??1;
            int pageSize = 10;
            List<Client> list = db.GetListByPage(pageIndex, pageSize, searchMsg, CType,Status);
            int rowCount = db.GetAllClient(searchMsg, CType).Count();
            var pageCount = 0;
            if (rowCount % pageSize != 0)
            {
                if (rowCount - pageSize < 0)
                {
                    pageCount = 1;
                }
                else
                {
                    pageCount = rowCount / pageSize + 1;
                }
            }
            else
            {
                pageCount = rowCount / pageSize;
            }
            var strResult = "{\"pageCount\":" + pageCount + ",\"CurrentPage\":" + pageIndex + ",\"list\":" + list.ToJsonString() + "}";
            return Json(strResult, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 修改客户类型
        /// </summary>
        /// <param name="id">客户ID</param>
        /// <param name="aimType">目标类型</param>
        /// <returns></returns>
        public JsonResult CTypeChange(int id,int aimType)
        {
            Client client = db.GetModel(id);
            client.CType = aimType;
            db.Save(client);
            return Json("OK");
        }
        /// <summary>
        /// 修改数据有效性
        /// </summary>
        /// <param name="id">客户ID</param>
        /// <returns></returns>
        public JsonResult StatusChange(int id)
        {
            Client client = db.GetModel(id);
            client.Status = !client.Status;
            db.Save(client);
            return Json("OK");
        }
        /// <summary>
        /// 新增客户
        /// </summary>
        /// <param name="id">客户ID</param>
        /// <returns></returns>
        public ViewResult CreateAndEdit(int id=0)
        {
            Client client = null;
            if (id != 0)
            {
                client = db.GetModel(id);
            }
            if (client == null)
                    client = new Client();
            return View(client);
        }
        /// <summary>
        /// 保存客户信息
        /// </summary>
        /// <param name="client">客户实体</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateAndEdit(Client client)
        {
            Client currentClient;
            if (client.CId == 0) { currentClient = new Client(); }
            else { currentClient = db.GetModel(client.CId); }
            currentClient.CName = client.CName;
            currentClient.Company = client.Company;
            currentClient.Mail = client.Mail;
            currentClient.Address = client.Address;
            currentClient.Phone = client.Phone;
            currentClient.Position = client.Position;
            currentClient.Department = client.Department;
            currentClient.Status = currentClient.Status??true;
            currentClient.EmpId = int.Parse(Session["currentUser"].ToString());
           currentClient.CType = Request["CType"]=="1"?1:0;
            currentClient.Remark = client.Remark;
            db.Save(currentClient);
            return Json("OK");
        }

        /// <summary>
        /// 删除一个客户
        /// </summary>
        /// <param name="id">客户ID</param>
        /// <returns></returns>
        public JsonResult Delete(int id)
        {
            db.Delete(id);
            return Json("yes");
        }
        /// <summary>
        /// 返回详细信息页面
        /// </summary>
        /// <param name="id">客户ID</param>
        /// <returns></returns>
        public ViewResult DetailMsg(int id)
        {
            ViewData["clientId"] = id;
            IEnumerable<ClientRelation> relations = db.GetRelations(id);
            return View(relations);
        }
        /// <summary>
        /// 返回一个客户
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult GetOneClient(int id)
        {
            Client client = db.GetModel(id);
            var str = "{\"client\":" + client.ToJsonString() + "}";
            return Json(str);
        }
        #endregion

        #region 交涉记录
        /// <summary>
        /// 保存交涉记录
        /// </summary>
        /// <param name="time">交涉时间</param>
        /// <param name="title">时间标题</param>
        /// <param name="Remark">备注</param>
        /// <param name="CId">客户ID</param>
        /// <param name="EmpId">用户ID</param>
        /// <param name="CRId">交涉记录ID</param>
        /// <returns></returns>
        public JsonResult AddCR (DateTime time, string title,string Remark,int CId,int CRId=0)
        {
            ClientRelation curRelation;
            if (CRId== 0) { curRelation = new ClientRelation(); }
            else { curRelation = db.GetCRModel(CRId); }
            curRelation.Title = title;
            curRelation.Date = time;
            curRelation.Remark = Remark;
            curRelation.EmpId = int.Parse(Session["currentUser"].ToString());
            curRelation.Status = true;
            curRelation.CId = CId;
            db.SaveCR(curRelation);
            return Json("OK");
        }
        /// <summary>
        /// 返回一个交涉记录
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult GetOneCR(int id)
        {
            ClientRelation cr = db.GetCRModel(id);
            var str = "{\"cr\":" + cr.ToJsonString() + "}";
            return Json(str);
        }
        /// <summary>
        /// 删除一条交涉记录
        /// </summary>
        /// <param name="id">交涉记录ID</param>
        /// <returns></returns>
        public JsonResult DeleteCR(int id)
        {
            db.DeleteCR(id);
            return Json("OK");
        }
        #endregion
    }
}

OA.Web/Views/Client/CreateAndEdit.cshtml
@model OA.Model.Client

@{
    ViewBag.Title = "CreateAndEdit";
    Layout = "~/Views/Shared/_JsCss.cshtml";
}
<script src="~/Scripts/jquery.validate.min.js"></script>

<h2>客户基本信息</h2>
<legend>@Html.ActionLink("返回", "Index")</legend>
<div class="col-sm-2"></div>
<div class="col-sm-10">
@using (Html.BeginForm("CreateAndEdit", "Client", FormMethod.Post, new { @class = "form-horizontal", id="clientForm" ,role = "form" }))
{
    <fieldset>
        <div class="form-group">
            @Html.HiddenFor(model => model.CId)
            <label class="col-sm-1 control-label" for="CName">姓名</label>
            <div class="col-sm-2">
                @Html.EditorFor(model => model.CName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.CName, "", new { @class = "text-danger" })
            </div>
            <label class="col-sm-1 control-label" for="Phone">电话</label>
            <div class="col-sm-3">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", required= "required" } })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label" for="Company">公司</label>
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label" for="Department">部门</label>
            <div class="col-sm-2">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <label class="col-sm-1 control-label" for="Mail">邮箱</label>
            <div class="col-sm-3">
                @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control", type = "email" } })
                @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label" for="Position">职位</label>
            <div class="col-sm-2">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
            </div>
            <label class="col-sm-1 control-label" for="CType">类型</label>
            <div class="col-sm-3">
                @Html.DropDownList("CType", new List<SelectListItem>
                    {
                      (new SelectListItem() {Text = "普通", Value = "0", Selected = true}),
                      (new SelectListItem() {Text = "重要", Value = "1", Selected =false})
                    }, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label" for="Address">地址</label>
            <div class="col-sm-6">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control"} })
            </div>
        </div>
        <div class="form-group co-sm-12">
            <label class="col-sm-1 control-label" for="Remark">备注</label>
            <div class="col-sm-6">
                @Html.TextAreaFor(model => model.Remark, 4,60, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-4"></div>
            <div class="col-sm-6">
                <input type="submit" value="保存" class="btn btn-default" />
            </div>
        </div>
    </fieldset>
}
</div>

<script type="text/javascript">
    $(function () {
        //提交事件
        $(".form-horizontal").submit(function (event) {
            event.preventDefault();
                if ($(this).valid()) {
                    $.ajax({
                        url: this.action,
                        type: this.method,
                        data: $(this).serialize(),
                        success: function (result) {
                            if (result !== null) {
                                alert("保存成功！");
                                window.location = "Index";
                            }
                        }
                    });
                }
                return false;
            });
        })
</script>

OA.Web/Views/Client/DetailMsg.cshtml
@model IEnumerable<OA.Model.ClientRelation>

@{
    ViewBag.Title = "DetailMsg";
    Layout = "~/Views/Shared/_JsCss.cshtml";
}

<h2>详细信息</h2>

<div style="height:100px;" id="detailMsg">
    <h4>@Html.ActionLink("返回", "Index")</h4>
</div>

<div class="col-sm-10" style="overflow:scroll;height:400px;width:750px;">
    <table class="table table-striped">
        <tr>
            <th>
                日期
            </th>
            <th>
                事件
            </th>
            <th>
                备注
            </th>
            <th>操作</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Remark)
                </td>
                <td>
                    <a href="javascript:void(0)" onclick="EditCR(@item.CRId)">编辑</a>
                   |<a href="javascript:void(0)" onclick="Delete(@item.CRId)">删除</a>
                </td>
            </tr>
        }
    </table>
</div>
<div class="col-sm-2">
        <input type="text" hidden="hidden" id="CRId" />
        <b>事件标题</b>
        <input type="text" class="form-control" id="title" />
        <b>日期</b>
        <input type="text" value="@DateTime.Now" id="CRDate" class="dateTimeStar form-control" data-date-format="yyyy-mm-dd">
        <b>备注</b>
        <textarea name ="remark"  cols=20 rows=8 id="remak"></textarea>
    <div class="col-sm-3"></div>
    <div class="col-sm-7" style="margin-top:5px;">
        <input type="button" value="保存" class="btn btn-default" id="addCR" />
    </div>
</div>

<script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
<script src="~/Scripts/bootstrap-datetimepicker.zh-CN.js"></script>
<link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<script type="text/javascript">
    $(function () {
        var clientId=@ViewData["clientId"];
        $.ajax({
            url: "GetOneClient?id="+clientId,
            type:"post",
            datatype:"json",
            success:function(data){
                if(data!=null)
                    var client=eval("(" + data + ")").client;
                var clientType=client.CType==1?"重要":"普通";
                $("#detailMsg").append("<table><tr><td>姓名："+client.CName+  "</td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td>公司："+client.Company+
                    "</td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td>部门："+client.Department+"</td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td>职位："+client.Position+
                    "</td></tr><tr><td>电话："+client.Phone+"</td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td>邮箱："+client.Mail+ 
                    "</td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td>地址："+client.Address+"</td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td><td>客户类型："+clientType+
                    "</td></tr><tr><td colspan='6'>备注："+client.Remark+"</td><td><a href='CreateAndEdit?id="+clientId+"'>编辑</td></tr></table>");
                $("#detailMsg").append('<input type="text" hidden="hidden" id="ClientId" value="'+clientId+'" />')
            }
        })

        $("#CRDate").datetimepicker({
            format: "yyyy-mm-dd",
            startView: 2,
            autoclose: true,//自动关闭
            //minDate: new Date(),
            minView: 2,//最精准的时间选择为日期0-分 1-时 2-日 3-月
            weekStart: 0,
            language: 'zh-CN',
            startDate: "@DateTime.Now",
            todayBtn: "linked"
        });
        $("#CRDate").datetimepicker("update", new Date());
        //$('#TimeSet').datetimepicker('setStartDate', new Date());

        $("#addCR").on("click",function(){
            if($("#title").val()==""||$("#title").val()==null||$("#CRDate").val()==null||$("#CRDate").val()==""){
                alert("存在未填项");
                return null;
            }
            $.ajax({
                url:"AddCR",
                type:"post",
                datatype:"json",
                data:{
                    time:$("#CRDate").val(),
                    title:$("#title").val(),
                    Remark:$("#remak").val(),
                    CId:clientId,
                    CRId:$("#CRId").val(),
                },
                success:function(data){
                    if(data!=null){
                        window.location = "DetailMsg?id="+clientId;
                    }
                }
            })
        })
    })

    function EditCR(id){
        $.ajax({
            url:"GetOneCR?id="+id,
            type:"post",
            datatype:"json",
            success:function(data){
                if(data!=null){
                    var cr = eval("(" + data + ")").cr;
                    $("#CRId").val(id);
                    $("#CRDate").val(cr.Date.substr(0,10));
                    $("#remak").val(cr.Remark);
                    $("#title").val(cr.Title);
                }
            }
        })
    }

    function Delete(id){
        $.ajax({
            url:"DeleteCR?id="+id,
            type:"post",
            datatype:"json",
            success:function(data){
                if(data!=null){
                    window.location = "DetailMsg?id="+$("#ClientId").val();
                }
            }
        })
    }
</script>

OA.Web/Views/Client/Index.cshtml
@model IEnumerable<OA.Model.Client>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_JsCss.cshtml";
}
<script src="~/Scripts/bootstrap-paginator.js"></script>
<script type="text/javascript">
    $(function () {
        loadPage();
            $("#serachBtn").click(function () {
                $("#List").empty();
                $("#pager").hide();
                loadPage();
                $("#pager").show();
            })
    })
    function addToList(data) {
        $("#List").empty();
        $("#List").append('<table id="data_table" class="table table-striped"> <thead><tr><th>客户姓名</th><th>公司</th><th>部门</th><th>职位</th><th>电话</th><th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;操  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;作</th></tr><tbody></tbody></table>');
            $.each(eval("(" + data + ")").list, function (index, item) { 
                statusStr = item.Status == 0 ? '<a class="status"  onclick="StatusChange(' + item.CId + ')">设为有效&nbsp;</a>' : '<a class="status"   onclick="StatusChange(' + item.CId + ')">置为无效&nbsp;</a>'
                typeStr = item.CType == 0 ? '<a class="ctype"  onclick="CTypeChange(' + item.CId + ',1)">设为重要&nbsp;</a>' : '<a class="ctype"  onclick="CTypeChange(' + item.CId + ',0)">设为普通&nbsp;</a>'
                allStr = '<a class="edit" id=' + item.CId + '  href="DetailMsg?id=' + item.CId + '">详细信息 </a> <a class="confirm-link" id="delete" href="#" onclick="deleteFunc(' + item.CId + ',\'' + item.CName + '\')">删除</a>'
                $("#data_table tbody").append('<tr><td>' + item.CName + '</td><td>' + item.Company + '</td><td>' + item.Department + '</td><td>' + item.Position + '</td><td>'
                    + item.Phone + '</td><td>' + statusStr +typeStr+allStr+ '</td></tr>');
            });
    }
    //删除数据
        function deleteFunc(clientId,clientName) {
            var r = confirm("确认删除"+clientName+"的基础信息及其所有接触记录？");
            if (r == true) {
                $.ajax({
                    url: "Delete?id=" + clientId,
                    datatype: "json",
                    type: "Post",
                    success: function (data) {
                        if (data == "yes") {
                            $("#List").empty();
                            $("#pager").empty();
                            loadPage();
                        }
                        else {
                            alert("删除失败");
                        }
                    }
                })
            }
        }
    //加载列表
        function loadPage() {
            $.ajax({
                url: "List_Json",
                datatype: "json",
                type: "Post",
                data: { searchMsg: $("#serachText").val(), CType: $("#CType").val(), Status: $("#Status").val() },
                success: function (data) {
                    if (data != null) {
                        addToList(data);
                        var pageCount = eval("(" + data + ")").pageCount; 
                        var currentPage = eval("(" + data + ")").CurrentPage;
                        var options = {
                            bootstrapMajorVersion: 2, 
                            currentPage: currentPage, 
                            totalPages: pageCount, 
                            itemTexts: function (type, page, current) {
                                switch (type) {
                                    case "first":
                                        return "首页";
                                    case "prev":
                                        return "上一页";
                                    case "next":
                                        return "下一页";
                                    case "last":
                                        return "末页";
                                    case "page":
                                        return page;
                                }
                            },
                            onPageClicked: function (event, originalEvent, type, page) {
                                $("#List").empty();
                                $("#pager").hide();
                                $.ajax({
                                    url: "List_Json",
                                    type: "Post",
                                    data: { page: page, searchMsg: $("#serachText").val(), CType: $("#CType").val(), Status: $("#Status").val() },
                                    success: function (data1) {
                                        if (data1 != null) {
                                            addToList(data1);
                                        }
                                        $("#pager").show();
                                    }
                                });
                            }
                        };
                        $("#pager").bootstrapPaginator(options);
                    }
                }
            });
        }

    //修改客户类型
        function CTypeChange(clientId,aimToType) {
            $.ajax({
                url: "CTypeChange",
                type: "post",
                data: { id: clientId, aimType: aimToType },
                success: function (data) {
                    if (data != null) {
                        loadPage();
                    }
                }
            })
        }
    //修改有效性
        function StatusChange(CId) {
            $.ajax({
                url: "StatusChange",
                type: "post",
                data: { id: CId },
                success: function (data) {
                    if (data != null) {
                        loadPage();
                    }
                }
            })
        }
</script>

<div class="input-group col-sm-2" style="margin-bottom:5px;margin-top:10px; position:relative">
        @Html.DropDownList("CType", new List<SelectListItem>
        {
            ( new SelectListItem() { Text="全部",Value="-1",Selected=true}),
            (new SelectListItem() { Text="普通",Value="0",Selected=false}),
            (new SelectListItem() { Text="重要",Value="1",Selected=false})
        }, new { @class = "form-control" })
</div>
<div class="input-group col-sm-2" style="margin-bottom:5px;margin-top:10px;position:relative">
    @Html.DropDownList("Status", new List<SelectListItem>
        {
            ( new SelectListItem() { Text="有效",Value="true",Selected=true}),
            (new SelectListItem() { Text="无效",Value="false",Selected=false})
        }, new { @class = "form-control" })
</div>
<div class="input-group col-sm-3" style="margin-bottom:5px;margin-top:10px;position:relative">
    <input type="text" class="form-control" id="serachText" placeholder="请输入客户姓名" style="width:150px;">
    <span class="input-group-btn">
        <button class="btn btn-info bt-search" id="serachBtn">查找</button>
        <button class="btn btn-info bt-search" style="margin-left:3px;color:white;">@Html.ActionLink("新增客户", "CreateAndEdit")</button>
    </span>
</div>
<div id="List"></div>
<div id="pager"></div>