OA.Web/Controllers/PositionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OA.Model;
using System.Text;
using OA.Common;

namespace OA.Web.Controllers
{
    public class PositionController : CommonController
    {
        PositionData db = new PositionData();
        /// <summary>
        /// 转到职位管理的首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// ajax 获取出职位树
        /// </summary>
        /// <returns></returns>
        public ActionResult PositionTree()
        {
            List<Position> topPosition = db.GetTopList();
            var str = PingPositionTree(topPosition);
            return Json(str, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 递归Ping 出职位列表
        /// </summary>
        /// <param name="position">职位列表</param>
        /// <returns></returns>
        public string PingPositionTree(List<Position> position)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("<ul>");
            foreach (var posit in position)
            {
                var sonList = posit.Position2.ToList();
                sb.AppendFormat("<li><span>{0}</span><a href='javascript:void(0);' onclick= 'EditClick({2})' class='myEdit' id={1}>编辑</a>", posit.PosName, posit.PositionId,posit.PositionId);
                if (sonList.Count() > 0)
                {
                    sb.Append(PingPositionTree(sonList));
                }
                sb.Append("</li>");
            }
            sb.Append("</ul>");
            return sb.ToString();
        }

        /// <summary>
        /// 得到部门信息传回JSon
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public  ActionResult Edit(string id)
        {
            Position posit = db.GetModel(int.Parse(id));
            EmployeeData emdb = new EmployeeData();
            var OperUser = posit.OperUser == null ? null : emdb.GetModel(int.Parse(posit.OperUser)).EmpName;
            //List<Position> positions = db.GetParentPost(int.Parse(id));
            var strResult = "{\"OperUser\":\"" + OperUser + "\",\"posit\":" + posit.ToJsonString() + "}";
            return Json(strResult);
        }
        /// <summary>
        /// 保存职位信息
        /// </summary>
        /// <param name="positionId">职位ID</param>
        /// <param name="posName">职位名</param>
        /// <param name="parentId">父级职位</param>
        /// <param name="remark">备注</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult CreateAndEditer(string positionId,string posName,string parentId,string remark)
        {
            Position posit;
            if (string.IsNullOrEmpty(positionId))
            { posit = new Position(); }
            else
            { posit = db.GetModel(int.Parse(positionId)); }
            posit.PosName = posName;
            if (string.IsNullOrEmpty(parentId))
            {
                posit.ParentId = null;
            }
            else
            {
                posit.ParentId = int.Parse(parentId);
            }
            posit.Remark = remark;
            posit.LastChangeTime = DateTime.Now;
            db.Save(posit);
            return Json("OK");
        }

        /// <summary>
        /// 删除职位
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult DeletePosition(string id)
        {
            int posId = int.Parse(id);
            Position posit = db.GetModel(posId);
            if (posit.Position2.ToList().Count()>0)
            {
                return Json("No");
            }
            else
            {
                List<Employee> emps = db.GetPositEmp(posId);
                foreach(Employee emp in emps)
                {
                    emp.PositionId = null;
                }
                db.Delete(posId);
                return Json("Yes");
            }
        }
        /// <summary>
        /// 获取当前职位可用的父职位 返回Json
        /// </summary>
        /// <param name="id">当前职位的ID</param>
        /// <returns></returns>
        public JsonResult DropDownParent(string id)
        {
            List<Position> positsList ;
            if (id == null || id == "" || id == "null")
            {
                positsList = db.GetAllPosition();
            }else
            {
                positsList = db.GetParentPosit(int.Parse(id));
            }
            var strResult = "{\"DropList\":" + positsList.ToJsonString() + "}";
            return Json(strResult, JsonRequestBehavior.AllowGet);
        }
    }
}

OA.Web/Views/Position/Index.cshtml
@model OA.Model.Position

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_JsCss.cshtml";
}

<script type="text/javascript">
    $(function () {
        //加载tree
        PositionTree();
        //填充默认下拉列表
        FullDropDown(null, null);
        //清除按钮，清除文本框的内容
        $("#Clear").on("click", function () {
            $("#currentId").val(null);
            $("#PosName,#OperUser,#LastChangeTime,#Remark").val("");
            //清空下拉及填充下拉
            FullDropDown("", "");
        })

        //删除按钮
        $("#Delete").on("click", function () {
            //没有选择部门时
            var currentId = $("#currentId").val()
            if (currentId == null || currentId == "") {
                alert("请选择一个部门！");
                return null;
            }
            //有选择的部门时
            $.ajax({
                url: "DeletePosition?id=" + $("#currentId").val(),
                datatype: "json",
                type: "post",
                success: function (data) {
                    if (data != null) {
                        if (data == "No") {
                            alert("存在子部门，禁止删除！");
                            return null;
                        }
                        $("#Clear").trigger("click");//点了删除之后清空所有文本框
                        //加载树
                        PositionTree();
                    }
                }
            })
        })

        //提交按钮
        $("#Submit").on("click", function (e) {
            e.preventDefault();
            var posName = $("#PosName").val();
            if (posName == null || posName == "") {
                alert("职位名不能为空！")
                return null;
            }
            Submit($("#currentId").val())
        })
    })
    //4.提交需要处理的事
    function Submit(id) {
        $.ajax({
            url: "CreateAndEditer",
            datatype: "json",
            type: "post",
            data: {
                posName: $("#PosName").val(),
                parentId: $("#ParentId").val(),
                remark: $("#Remark").val(),
                positionId: id
            },
            success: function (data) {
                if (data != null) {
                    PositionTree();
                    $("#Clear").trigger("click");
                    alert("提交成功！")
                }
            }
        })
    }
    //3.编辑点击事件
    function EditClick(id) {
        $("#currentId").val(id);
        $.ajax({
            url: "Edit?id=" + id,
            datatype: "json",
            type: "post",
            async: false,
            success: function (data) {
                if (data != null) {
                    var posit = eval("(" + data + ")").posit;
                    var operUser = eval("(" + data + ")").OperUser;
                    //处理下拉列表 ping出来
                    FullDropDown(posit.PositionId, posit.ParentId);
                    //填充数据
                    $("#PosName").val(posit.PosName);
                    $("#OperUser").val(operUser);
                    if (posit.LastChangeTime != null) {
                        var lastChangeTime = posit.LastChangeTime.split("T");//分割时间，显示到天
                        $("#LastChangeTime").val(lastChangeTime[0]);
                    }
                    $("#Remark").val(posit.Remark);
                }
            }
        })
    }

    //2.处理下拉列表
    function FullDropDown(selfId, parentId) {
        $("#ParentId").empty();
        $.ajax({
            url: "DropDownParent?id=" + selfId,
            datatype: "json",
            type: "post",
            success: function (data) {
                if (data != null) {
                    var dropList = eval("(" + data + ")").DropList;
                    $("#ParentId").append("<option value=''>--请选择--</option>")
                    $.each(dropList, function (index, item) {
                        $("#ParentId").append("<option value='" + item.PositionId + "'>" + item.PosName + "</option>")
                    });
                    $("#ParentId").val(parentId);
                }
            }
        })
    }
    //1.用以刷新树
    function PositionTree() {
        $(".tree.well ul").empty();//先清空当前树
        $.ajax({
            url: "PositionTree",
            datatype: "json",
            type: "Post",
            success: function (result) {
                if (result !== null) {
                    $(".tree.well").append(result);
                    $('.tree li:has(ul)').addClass('parent_li').find(' > span').attr('title', 'Collapse this branch');
                    $('.tree li.parent_li > span').on('click', function (e) {
                        var children = $(this).parent('li.parent_li').find(' > ul > li');
                        if (children.is(":visible")) {
                            children.hide('fast');
                            $(this).attr('title', 'Expand this branch').find(' > i').addClass('icon-plus-sign').removeClass('icon-minus-sign');
                        } else {
                            children.show('fast');
                            $(this).attr('title', 'Collapse this branch').find(' > i').addClass('icon-minus-sign').removeClass('icon-plus-sign');
                        }
                        e.stopPropagation();
                    });
                }
            }
        });
    }
</script>

<div style="padding-top:70px;">
    <div class="tree well col-sm-4" style="background-color:white;border:0px;width:300px;padding:0px;">
        <h3>当前所有职位：</h3>
    </div>
    <div class="col-sm=8" style="padding-top:60px;">
        @using (Html.BeginForm("CreateAndEditer", "Position", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <fieldset>
                <div class="form-group">
                    <input id="currentId" type="hidden" />
                    <label class="col-sm-2 control-label" for="PosName">职位名</label>
                    <div class="col-sm-3">
                        @Html.EditorFor(model => model.PosName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    </div>
                    <label class="col-sm-3 control-label" for="ParentId">上级职位</label>
                    <div class="col-sm-3">
                        @Html.DropDownList("ParentId", new List<SelectListItem>
                    {
                      (new SelectListItem() {Text = "--请选择--", Value = "", Selected = true})
                    }, new { @class = "form-control", onselect = "false" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="OperUser">上次修改人</label>
                    <div class="col-sm-3">
                        @Html.EditorFor(model => model.OperUser, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    </div>
                    <label class="col-sm-3 control-label" for="LastChangeTime">上次修改时间</label>
                    <div class="col-sm-3">
                        @Html.EditorFor(model => model.LastChangeTime, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="Remark">备注</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(model => model.Remark, 4, 60, new { htmlAttributes = new { @class = "form-control", width = "440px" } })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-4"></div>
                    <div class="col-sm-8">
                        <input type="button" value="清空" id="Clear" class="btn btn-default" />
                        <input type="submit" value="提交" id="Submit" class="btn btn-default" />
                        <input type="button" value="删除职位"  id="Delete" class="btn btn-default" />
                    </div>
                </div>
            </fieldset>
        }
    </div>
</div>